
services:
  postgres:
    image: postgres:18-alpine
    container_name: pantry_mate_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pantrymate_orderpayment
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - monitoring

volumes:
  postgres-data:

networks:
  monitoring:
