server:
  port: 8084
spring:
  application:
    name: order-payment-service
  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/pantrymate_orderpayment
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

toss:
  secret-key: ${TOSS_SECRET_KEY}

internal:
  api:
    secret: ${INTERNAL_API_SECRET}